### ISSUE TITLE
Influx needed for historical data?

### ISSUE THREAD

**Issue by lahomagit** [Tucsky/aggr-server#10]
I'm able to connect my aggr client to my aggr-server fine, but am struggling to get the client to fetch historical data from my server. I currently have the server recording to files, rather than Influx, and can see the data being recorded into said files. Do I need to switch over to Influx as the storage method? I saw this line in files.js that made me think this may be the case: "console.error('[storage/file] historical data request not supported by this storage type (raw trade files)')"

**Comment by Tucsky** [comment]
You guessed it, In a previous version the client was consuming raw trades data provided by the files storage but not anymore
Files storage is more for backup and archive
Influx storage is what we use for serving data on demand, data which is already prepared (grouped into specific timeframe in real time)

If you can't use influx you could complete the fetch function (in files.js) that will return the data grouped into bars
- loop through the files in desired range (https://github.com/Tucsky/SignificantTrades/blob/feature/server/src/storage/files.js#L131)
- loop through the trades in each files
- create bars out of them (summing by time depending on timeframe)


I didn't bothered doing it because it is too resource intensive for the number of requests I have but for personal use it could work :)

**Comment by lahomagit** [comment]
Thanks for the reply! I have Influx working now, but for some reason the server still isn't advertising/supplying historical data (should be ~8 hours worth) for the pair I'm testing:

[storage] Using "influx" storage solution
[storage] Set "influx" as primary storage for API
[storage/influx] connecting to localhost:8086 on db "significant_trades"
[storage] Using "files" storage solution
[storage/FilesStorage] destination folder: ./data
[storage] all storage ready
...
[storage/influx] create retention policy aggr_10s (duration 13h)
[storage/influx] create retention policy aggr_30s (duration 1d)
[storage/influx] create retention policy aggr_1m (duration 3d)
[storage/influx] create retention policy aggr_3m (duration 10d)
[storage/influx] create retention policy aggr_5m (duration 17d)
[storage/influx] create retention policy aggr_15m (duration 52d)
[storage/influx] create retention policy aggr_30m (duration 104d)
[storage/influx] create retention policy aggr_1h (duration 208d)
[storage/influx] create retention policy aggr_2h (duration 416d)
[storage/influx] create retention policy aggr_4h (duration 833d)
[storage/influx] create retention policy aggr_6h (duration 1250d)
[storage/influx] create retention policy aggr_1d (duration 5000d)
[server] scheduling first save to InfluxStorage,FilesStorage in 2s 297ms...
[server] http server listening at localhost:3000 

│      COINBASE:OP-USD       │ '3.5K'  │  '5/min'   │  '5s 1ms'   │ '1h' │
│        FTX:OP-PERP         │ '80.5K' │ '128/min'  │ '1s 266ms'  │ '1h' │
│       BINANCE:opusdt       │ '104K'  │ '166/min'  │ '10s 250ms' │ '1h' │
│        BYBIT:OPUSDT        │ '103K'  │ '165/min'  │ '1s 988ms'  │ '1h' │
│ BINANCE_FUTURES:opusd_perp │ '11.2K' │  '17/min'  │ '23s 692ms' │ '1h' │
│   BINANCE_FUTURES:opusdt   │ '739K'  │ '1.2K/min' │   '401ms'   │ '1h' │
│       BITMEX:OPUSDT        │   52    │  '0/min'   │ '18m, 17s'  │ '1h' │
│     BYBIT:OPUSDT-SPOT      │  '2K'   │  '3/min'   │ '1s 810ms'  │ '1h' │
│        FTX:OP-0930         │   244   │  '0/min'   │ '14m, 22s'  │ '1h' │
│        BITMEX:OPUSD        │   15    │  '0/min'   │ '18m, 17s'  │ '1h' │

Pair search in my client doesn't show OPUSD as having historical data, and no historical data is fetched when I zoom out on the chart. I'm using "API_URL=http://localhost:3000/{from}/{to}/{timeframe}/{markets}". When I try "API_URL=http://localhost:3000/historical/{from}/{to}/{timeframe}/{markets}" the chart watermark becomes "Undefined" and it won't refresh or connect/disconnect pairs (I assume because it can't find any pairs with historical data?).

**Comment by lahomagit** [comment]
Turns out I just had to set my environment variables properly:
API_URL=http://localhost:3000/ API_SUPPORTED_TIMEFRAMES=10,30,60,180,300,900,1260,1800,3600,7200,14400,21600,28800,43200,86400

Thanks for your work!
