### ISSUE TITLE
How to backfill effectively?

### ISSUE THREAD

**Issue by zlex7** [Tucsky/aggr-server#20]
Not just historicals like with coinalize script, but if server goes down for an hour and recoverMissingTrades doesn't fill in all the holes. Can coinalize script work for this as well? Thanks!

**Comment by Tucsky** [comment]
If one server goes down, have another server running in backup.
That's the most accurate way as pulling trade data directly through exchang's API is slow and in some case, not even possible

My backup server gets the raw trades files only, so when I need I download them and reimport the missing range into influx from those files

**Comment by adeacetis** [comment]
Hello @zlex7,

I hope you found the answer you were looking for. 

If you have more questions, join us on Discord. That would be easier to discuss detailed technical topics. We'd love to have you there.

Aggr.Trade Discord Server: https://discord.gg/ZA6CFMkq

Kind regards

**Comment by zlex7** [comment]
yoo this is awesome! Joining looking forward to meeting yall :)
