### ISSUE TITLE
Utilizing Aggr-Server for Storing and Analyzing Binance Perpetual and Spot Trade Data

### ISSUE THREAD

**Issue by alexrmacleod** [Tucsky/aggr-server#29]
Hello Aggr-Server contributors! I have a specific requirement where I need to store all trade data from Binance perpetual and spot markets starting from 2020 up until the present. My goal is to compute, normalize, and calculate percentage deviations between the cumulative volume deltas (CVDs) over this time period and then visualize the results through charts.

I'm interested in leveraging Aggr-Server for this task. Could you please provide guidance on how I can utilize Aggr-Server to store the trade data, compute CVDs, normalize them, calculate percentage deviations, and generate the necessary charts? Additionally, if there are any potential roadblocks or limitations I should be aware of in this process, please let me know.

Thank you for your assistance and expertise!

**Comment by adeacetis** [comment]
Please join our Discord so we can talk about it https://discord.gg/k2zyckRN. Say hello in #general
