### ISSUE TITLE
Cannot connect to influxdb

### ISSUE THREAD

**Issue by horviskoadrianko** [Tucsky/aggr-server#3]
Aggr-server cannot connect to influxdb. But i can connect to influxdb with terminal. Maybe it is because of new influxdb server version
Running with docker

st-server | [storage/influx] connecting to localhost:8086
st-server | [storage/influx] connect ECONNREFUSED 127.0.0.1:8086... retrying in 1s

**Comment by Tucsky** [comment]
Influx 1.8 is what we use indeed but I can give 2.x a shot if worth it :)
