### ISSUE TITLE
Add BINANCE:BTCDUSD CVD historical data

### ISSUE THREAD

**Issue by yuuuuk2** [Tucsky/aggr-server#38]
I would like to create a cvd for Binance:btcfdusd, but I can't because there is no historical data. Is it possible to have it added?

**Comment by adeacetis** [comment]
Hello @yuuuuk2 

Thank you for the heads up.

@Tucsky Looks like Binance switched trading from BUSD to FDUSD ( First Digital USD ) 

BTC_BUSD: $18m (24h volume)
![image](https://github.com/Tucsky/aggr-server/assets/20586054/caf9d606-06b7-4072-a91c-3e813e8b59dc)
 
BTC_FDUSD: $1.5bn (24h volume)
![image](https://github.com/Tucsky/aggr-server/assets/20586054/51e410b9-e348-48e3-bdde-d788c9693ae3)

**Comment by yuuuuk2** [comment]
thank you so much!
