### ISSUE TITLE
[Request] Wildcard Pairs / Asset+Quote Pairings

### ISSUE THREAD

**Issue by grainz** [Tucsky/aggr-server#7]
I was going to create two different requests for this on both the charts and server but decided to just ask here.
Is it possible to pull pairs baed on either a wildcard or Asset+Quote pairing?
Example: I want all pairs on Binance or Binance US that end with USD or USDT or BINANCE:.\*/USDT,BINANCE_US:.\*/USD
This would also play into the API_SUPPORTED_PAIRS variable in the charts.

**Comment by Tucsky** [comment]
Disabling the grouping let you use regex in the search box
![image](https://user-images.githubusercontent.com/5738336/151350251-83e24cb8-f25c-4ecf-b97e-1260567296ec.png)

You can just type `(binance|binance_us):.*usdt?$` in the search box with grouping disabled and add all the results

![image](https://user-images.githubusercontent.com/5738336/151350337-84eae8bc-1d50-4ff9-b5a0-f2b12bda6125.png)

**Comment by grainz** [comment]
I definitely didn't know that about the search box in the chart options. Good unintended tip :)

I'll definitely see what I may be able to come up with for aggr-server in a PR. Thank you for your response.
