### ISSUE TITLE
Unauthorized error occurred

### ISSUE THREAD

**Issue by matthewwwz** [Tucsky/aggr-server#8]
Hey, after installing the server and Influxdb and running node index, it's impossible to log in!

`[storage/influx] connecting to localhost:8086
[storage/influx] A 401 Unauthorized error occurred: {"code":"unauthorized","message":"Unauthorized"}... retrying in 1s`

**Comment by Tucsky** [comment]
Have you installed influx 2 ? or 1

This repo only works with influx 1.* and in that case maybe http auth is enabled on this influx instance
```
{
... in the config.json ...
"influxHost": "http://user:password@host"
}
```

**Comment by VIEWVIEWVIEW** [comment]
> Have you installed influx 2 ? or 1
> 
> This repo only works with influx 1.* and in that case maybe http auth is enabled on this influx instance
> 
> ```
> {
> ... in the config.json ...
> "influxHost": "http://user:password@host"
> }
> ```
> 
> I am planning to upgrade to influx 2 [here](https://github.com/Tucsky/aggr-server/tree/feature/influx2) I have yet to get back to it lol

Wouldn't switching to timescaledb make more sense, since it enables horizontal scaling via "[chunking](https://docs.timescale.com/timescaledb/latest/overview/core-concepts/distributed-hypertables/#distributed-databases-and-nodes)" (it's similar to sharding; afaik influxdb only supports sharding in the pricey enterprise version)?

**Comment by adeacetis** [comment]
Hello all, 
I went away and I "fixed" the Docker implementation using the old InfluxDb version.

Here's the PR:
https://github.com/Tucsky/aggr-server/pull/13

Reviews welcome.
Cheers,

**Comment by adeacetis** [comment]
@matthewwwz did you manage to run this ? Can we close this issue ?
